
--2022-07-11 新增商户信息表字段长度调整
ALTER TABLE CMS_SELLER_INFORMATION
  MODIFY ("CONTACT_PERSON" VARCHAR2(128 BYTE) )
  MODIFY ("CONTACT_MOBILE_NUMBER" VARCHAR2(128 BYTE) )
  MODIFY ("CONTACT_TELEPHONE_NUMBER" VARCHAR2(128 BYTE) )
  MODIFY ("COPORATE_EMAIL" VARCHAR2(128 BYTE) );

--插入生成支付机构报表定时任务job，执行时间是每个月一号早上八点，
INSERT INTO "SYS_TASK" ("ID","TASK_NAME","GROUP_NAME","EXEC_TYPE","CRON_EXP","TASK_TARGET","PARAMS","STATUS","CREATE_DATE","CREATE_BY","UPDATE_BY","REMARKS",
                        "EXECUTE_ADDRESS","DISTRIBUTE_TYPE","RUN_STATUS_THRESHOLDS","RUN_STATUS"
)
VALUES
('36','生成支付机构报表',	'order','0',	'0 0 8 1 * ? ','generateReportJob',	NULL,'1',SYSDATE,'1','1','1',	NULL,'0',	'0','1' 	);


--插入商户信息文件生成定时任务job，执行时间是每天早上8:20，生成昨天新增的数据，
INSERT INTO "SYS_TASK" ("ID","TASK_NAME","GROUP_NAME","EXEC_TYPE","CRON_EXP","TASK_TARGET","PARAMS","STATUS","CREATE_DATE","CREATE_BY","UPDATE_BY","REMARKS",
                        "EXECUTE_ADDRESS","DISTRIBUTE_TYPE","RUN_STATUS_THRESHOLDS","RUN_STATUS"
)
VALUES
('37','商户信息文件生成',	'order','0',	'0 20 8 * * ? ','generateSellerInfoFileJob',	NULL,'1',SYSDATE,'1','1','1',	NULL,'0',	'0','1' 	);

--添加商户表 导入标识字段
ALTER TABLE "CMS_SELLER_INFORMATION"
  ADD ("IMPORT_FLAG" VARCHAR2(2) DEFAULT 0 );
COMMENT ON COLUMN "CMS_SELLER_INFORMATION"."IMPORT_FLAG" IS '导入标识 0:正常入库 1:导入入库';

--插入商户信息文件生成定时任务job，执行时间是每天早上8:20，生成昨天新增的数据，
INSERT INTO "SYS_TASK" ("ID","TASK_NAME","GROUP_NAME","EXEC_TYPE","CRON_EXP","TASK_TARGET","PARAMS","STATUS","CREATE_DATE","CREATE_BY","UPDATE_BY","REMARKS", "EXECUTE_ADDRESS","DISTRIBUTE_TYPE","RUN_STATUS_THRESHOLDS","RUN_STATUS")
VALUES
('38','平台初次存量卖家信息入库',	'order','0',	'0 30 8 * * ? ','readSellerInfoFileJob',	NULL,'1',SYSDATE,'1','1','1',	NULL,'0',	'0','1' 	);


alter table CMS_SELLER_INFORMATION
    add SELLER_STORE_STATUS VARCHAR2(2)
/

comment on column CMS_SELLER_INFORMATION.SELLER_STORE_STATUS is '商户销户状态 01-封铺，02-正常销户'
/

--添加扣款账户字段
ALTER TABLE "CMS_SELLER_INFORMATION"
  ADD ("DEBIT_ACCOUNT" VARCHAR2(100) );
COMMENT ON COLUMN "CMS_SELLER_INFORMATION"."DEBIT_ACCOUNT" IS '扣款账户';

