
--CMS_COGNOS_REPORT 新加三个字段
ALTER TABLE "CMS_COGNOS_REPORT"
  ADD ("IN_CTRY_EXCHANGE_RATE" VARCHAR2(150) )
  ADD ("IN_CTRY_FX_DEAL_NUMBER" VARCHAR2(150) )
  ADD ("USD_AMOUNT" VARCHAR2(150) );
COMMENT ON COLUMN "CMS_COGNOS_REPORT"."IN_CTRY_EXCHANGE_RATE" IS '外币转美元汇率';
COMMENT ON COLUMN "CMS_COGNOS_REPORT"."IN_CTRY_FX_DEAL_NUMBER" IS '交易编号';
COMMENT ON COLUMN "CMS_COGNOS_REPORT"."USD_AMOUNT" IS '等效美元金额';

--添加国际货币配置表配置表
CREATE TABLE "CMS_INTERNATIONAL_CURRENCY"
(	"ID" NUMBER(11,0) generated as identity
     primary key,
   "CURRENCY" VARCHAR2(255),
   "CREATE_DATE" VARCHAR2(50),
   "UPDATE_DATE" VARCHAR2(50),
   "CREATOR" VARCHAR2(255),
   "MODIFIER" VARCHAR2(255)
);
comment on table CMS_INTERNATIONAL_CURRENCY is '国际货币配置表'
/
comment on column CMS_INTERNATIONAL_CURRENCY.CURRENCY is '币种'
/
